export const FETCH_BOOK_REQUEST ='FETCH_BOOK_REQUEST';
export const FETCH_BOOK_SUCCESS ='FETCH_BOOK_SUCCESS';
export const FETCH_BOOK_FAILURE ='FETCH_BOOK_FAILURE';
export const SEARCH_BOOK ='SEARCH_BOOK';
